name: Build and upload preview build

on:
  pull_request:
    branches: [ main ]
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build windows x64
      run: dotnet publish -c Release --self-contained -r win-x64 -o packages/windows/x64 -p:PublishSingleFile=true
    - name: Install signing tool
      run: dotnet tool install --global AzureSignTool
    - name: Digitally sign executable
      env:
        CERT_SECRET: ${{ secrets.AZUREKEYVAULTCLIENTSECRET }}
      run: azuresigntool sign -kvt b5dc9f10-7402-4a62-8000-73efe61b1c16 -kvu "https://punk-hsm-vault.vault.azure.net/" -kvi "32a1a1bf-ce05-48fc-80fb-83ed5e95029f" -kvs "$CERT_SECRET" -kvc "PunkSecurity-CodeSigningCert-2022" -tr http://timestamp.globalsign.com/tsa/r6advanced1 -v ./packages/windows/x64/SMBeagle.exe
    - name: Upload windows x64
      uses: actions/upload-artifact@v2
      with:
        name: windows-x64
        path: packages/windows/x64/*
