name: Build and upload preview build

on:
  pull_request:
    branches: [ main ]
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build windows x64
      run: dotnet publish -c Release --self-contained -r win-x64 -o packages/windows/x64 -p:PublishSingleFile=true
    - name: Upload windows x64
      uses: actions/upload-artifact@v2
      with:
        name: windows-x64
        path: packages/windows/x64/*
